### PR TITLE
Extract types, and add JSDoc comments

### PR DESCRIPTION
**Pull request by recursive-beast**
Extracted typescript types into their own files, grouped into a `src/types` folder, and added JSDoc comments to different functions.
Additionally, updated the description for `--matchfield` since the argument is a list of strings rather than a single string of options separated by commas.

### CODE REVIEW

**Review by suzuya1331 — CHANGES_REQUESTED** [review]
Make sure to provide detailed information about what did you do ,all the tests used and update the readme file.

**Comment by suzuya1331** [comment]
@recursive-beast can you resolve the conflicts @recursive-beast

**Comment by recursive-beast** [comment]
@suzuya1331 done

**Review by suzuya1331 — APPROVED** [review]
good job

**Pull request merged**
